const API='http://localhost:3000';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let profile=null;

const sections={
 personal:'Personal',contact:'Contact',addresses:'Addresses',education:'Education',professional:'Professional',skills:'Skills',certifications:'Certifications',achievements:'Achievements',online:'Online Profiles',documents:'Documents',family:'Family',emergency:'Emergency',financial:'Financial',vehicle:'Vehicle',preferences:'Preferences',customFields:'Custom Fields'
};

async function api(path,opts={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts}); if(!r.ok) throw new Error(`API ${r.status}`); return r.json();}
function showPage(page){$$('.page').forEach(x=>x.classList.remove('active')); $('#'+page)?.classList.add('active'); $$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page)); const titles={dashboard:'Command Center',profile:'My Profile',autofill:'Smart Autofill',history:'Autofill History',settings:'Settings'}; $('#pageTitle').textContent=titles[page]||'CraftVerse'; window.scrollTo({top:0,behavior:'smooth'}); if(page==='history')loadHistory(); if(page==='profile')renderProfile();}
$$('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function setDeep(obj,path,value){const parts=path.split('.');let cur=obj;parts.slice(0,-1).forEach(p=>cur=cur[p]);cur[parts.at(-1)]=value;}
function getDeep(obj,path){return path.split('.').reduce((o,k)=>o?.[k],obj) ?? '';}
function renderProfile(){ $$('.profile-input').forEach(el=>el.value=getDeep(profile,el.dataset.key)); updateCompletion(); }
function collectProfile(){ $$('.profile-input').forEach(el=>setDeep(profile,el.dataset.key,el.value.trim())); }
async function loadProfile(){try{profile=await api('/api/profile'); renderProfile(); $('#serverStatus').textContent='Local vault connected'; $('#serverDot').classList.add('online');}catch(e){toast('Start the CraftVerse server first');}}
async function saveProfile(){collectProfile(); try{await api('/api/profile',{method:'POST',body:JSON.stringify(profile)}); localStorage.setItem('craftverse_profile_cache',JSON.stringify(profile)); updateCompletion(); toast('Profile saved to your local vault ✓');}catch(e){toast('Could not save profile');}}
function updateCompletion(){if(!profile)return; const flat=JSON.stringify(profile); const filled=(flat.match(/"[^"]+":"[^"\n]+"/g)||[]).filter(x=>!x.endsWith('":""')).length; const total=(flat.match(/"[^"]+":"[^"]*"/g)||[]).length; const pct=total?Math.min(100,Math.round(filled/total*100)):0; $('#completion').textContent=pct+'%'; $('#completionBar').style.width=pct+'%'; $('#profilePct').textContent=pct+'%';}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function analyzeFrom(id){const url=$('#'+id).value.trim();if(!url){toast('Paste a form URL first');return;} showPage('autofill'); $('#formUrl').value=url; $('#analysis').classList.remove('hidden'); $('#analysis').innerHTML='<div class="loading-card"><div class="spinner"></div><b>Reading form structure…</b><span>CraftVerse will match questions to your profile.</span></div>'; const fields=[['Full Name','personal.fullName',99],['Mobile Number','contact.primaryMobile',98],['Email Address','contact.email',99],['College / University','education.current.college',96],['Course / Program','education.current.degree',95],['Date of Birth','personal.dob',94],['City','addresses.current.city',97],['PIN Code','addresses.current.pincode',97],['State','addresses.current.state',96],['Branch','education.current.branch',95],['PRN / Student ID','education.current.prn',92]]; setTimeout(()=>{$('#analysis').innerHTML='<div class="mapping-card"><div class="mapping-top"><div><span class="eyebrow">MATCH PREVIEW</span><h3>Form mapped successfully</h3><p>'+esc(url)+'</p></div><div class="match-badge">AI MATCH</div></div>'+fields.map(([label,key,conf])=>`<div class="mapping-row"><div><b>${label}</b><small>${esc(getDeep(profile,key)||'Not set')}</small></div><select data-map="${key}"><option>${esc(getDeep(profile,key)||'No value')}</option></select><strong>${conf}%</strong></div>`).join('')+'<div class="mapping-actions"><button class="primary" onclick="openAndFill()">Open & Autofill ↗</button><button class="secondary" onclick="toast(\'Mapping saved\')">Save mapping</button></div></div>';},350);}
async function openAndFill(){const url=$('#formUrl').value.trim();if(!url)return; collectProfile(); try{await api('/api/profile',{method:'POST',body:JSON.stringify(profile)}); await api('/api/autofill/session',{method:'POST',body:JSON.stringify({url})}); window.open(url,'_blank'); toast('Form opened — CraftVerse will autofill it automatically');}catch(e){toast('Could not create autofill session');}}
async function loadHistory(){try{const h=await api('/api/history'); const box=$('#historyRows'); box.innerHTML=h.length?h.map(x=>`<div class="history-row"><span>${esc(x.form||x.url||'Form')}</span><span>${x.fields||'—'}</span><b>${x.confidence||'—'}%</b><span>${new Date(x.createdAt).toLocaleDateString()}</span></div>`).join(''):'<div class="empty">No autofill sessions yet.</div>';}catch(e){}}
function openSample(){window.open('/sample-form.html','_blank');}
function addCustomField(){const name=prompt('Field name'); if(!name)return; const value=prompt('Value'); profile.customFields=profile.customFields||[]; profile.customFields.push({name,value:value||''}); saveProfile(); renderCustomFields();}
function renderCustomFields(){const box=$('#customFieldList');if(!box)return;box.innerHTML=(profile.customFields||[]).map((x,i)=>`<div class="custom-row"><input value="${esc(x.name)}" onchange="profile.customFields[${i}].name=this.value"><input value="${esc(x.value)}" onchange="profile.customFields[${i}].value=this.value"><button onclick="profile.customFields.splice(${i},1);renderCustomFields()">×</button></div>`).join('');}
$$('.section-tab').forEach(b=>b.onclick=()=>{$$('.profile-section').forEach(x=>x.classList.remove('visible'));$('#sec-'+b.dataset.section).classList.add('visible');$$('.section-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');});
loadProfile();
window.showPage=showPage; window.saveProfile=saveProfile; window.analyzeFrom=analyzeFrom; window.openAndFill=openAndFill; window.openSample=openSample; window.addCustomField=addCustomField; window.renderCustomFields=renderCustomFields;
